/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as BuildStoryRouteImport } from './routes/build-story'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardWidgetsWidgetIdRouteImport } from './routes/dashboard/widgets/$widgetId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildStoryRoute = BuildStoryRouteImport.update({
  id: '/build-story',
  path: '/build-story',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/dashboard/leads',
  path: '/dashboard/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWidgetsWidgetIdRoute =
  DashboardWidgetsWidgetIdRouteImport.update({
    id: '/dashboard/widgets/$widgetId',
    path: '/dashboard/widgets/$widgetId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/build': typeof BuildRoute
  '/build-story': typeof BuildStoryRoute
  '/design-system': typeof DesignSystemRoute
  '/examples': typeof ExamplesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/widgets/$widgetId': typeof DashboardWidgetsWidgetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/build': typeof BuildRoute
  '/build-story': typeof BuildStoryRoute
  '/design-system': typeof DesignSystemRoute
  '/examples': typeof ExamplesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/widgets/$widgetId': typeof DashboardWidgetsWidgetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/build': typeof BuildRoute
  '/build-story': typeof BuildStoryRoute
  '/design-system': typeof DesignSystemRoute
  '/examples': typeof ExamplesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/widgets/$widgetId': typeof DashboardWidgetsWidgetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/build'
    | '/build-story'
    | '/design-system'
    | '/examples'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/dashboard/leads'
    | '/dashboard/'
    | '/dashboard/widgets/$widgetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/build'
    | '/build-story'
    | '/design-system'
    | '/examples'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/dashboard/leads'
    | '/dashboard'
    | '/dashboard/widgets/$widgetId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/build'
    | '/build-story'
    | '/design-system'
    | '/examples'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/dashboard/leads'
    | '/dashboard/'
    | '/dashboard/widgets/$widgetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuildRoute: typeof BuildRoute
  BuildStoryRoute: typeof BuildStoryRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ExamplesRoute: typeof ExamplesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWidgetsWidgetIdRoute: typeof DashboardWidgetsWidgetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-story': {
      id: '/build-story'
      path: '/build-story'
      fullPath: '/build-story'
      preLoaderRoute: typeof BuildStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/dashboard/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/widgets/$widgetId': {
      id: '/dashboard/widgets/$widgetId'
      path: '/dashboard/widgets/$widgetId'
      fullPath: '/dashboard/widgets/$widgetId'
      preLoaderRoute: typeof DashboardWidgetsWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuildRoute: BuildRoute,
  BuildStoryRoute: BuildStoryRoute,
  DesignSystemRoute: DesignSystemRoute,
  ExamplesRoute: ExamplesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWidgetsWidgetIdRoute: DashboardWidgetsWidgetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
