"""add_build_progress_fields_to_widgets

Revision ID: 5d7bd7635b92
Revises: d03a11720f6d
Create Date: 2026-07-22 03:00:24.866611
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d7bd7635b92'
down_revision: Union[str, None] = 'd03a11720f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('build_stage', sa.String(length=50), nullable=True))
    op.add_column('widgets', sa.Column('build_progress', sa.Float(), nullable=True))
    op.add_column('widgets', sa.Column('build_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'build_error')
    op.drop_column('widgets', 'build_progress')
    op.drop_column('widgets', 'build_stage')
    # ### end Alembic commands ###
