"""fix user_id type

Revision ID: 5d8a0f5e10b3
Revises: bef37ed6fedf
Create Date: 2026-07-04 10:06:05.582941
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d8a0f5e10b3'
down_revision: Union[str, None] = 'bef37ed6fedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widgets', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('widgets_user_id_fkey'), 'widgets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('widgets_user_id_fkey'), 'widgets', 'users', ['user_id'], ['id'])
    op.alter_column('widgets', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
