"""add visual_language column

Revision ID: c436ec5a63f5
Revises: 5d7bd7635b92
Create Date: 2026-07-22 20:48:01.440090
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c436ec5a63f5'
down_revision: Union[str, None] = '5d7bd7635b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('visual_language', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'visual_language')
    # ### end Alembic commands ###
