"""remove source_code from widgets

Revision ID: d03a11720f6d
Revises: 5d8a0f5e10b3
Create Date: 2026-07-05 02:03:10.111357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd03a11720f6d'
down_revision: Union[str, None] = '5d8a0f5e10b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'source_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('source_code', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
